#!/bin/bash

# 🚀 CyberCode - Quick Start Guide
# Guía rápida de inicio para desarrolladores

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      🔐 CyberCode - Guía Rápida de Inicio                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 PASO 1: Configurar Firebase"
echo "================================"
echo ""
echo "1. Ve a https://console.firebase.google.com"
echo "2. Crea un nuevo proyecto (o usa uno existente)"
echo "3. En Project Settings (⚙️) → General → Tu aplicación"
echo "4. Haz clic en </> (Web) y copia la configuración"
echo "5. Crea archivo .env.local en la raíz del proyecto"
echo "6. Pega tu configuración de Firebase:"
echo ""
echo "   REACT_APP_FIREBASE_API_KEY=..."
echo "   REACT_APP_FIREBASE_AUTH_DOMAIN=..."
echo "   REACT_APP_FIREBASE_PROJECT_ID=..."
echo "   REACT_APP_FIREBASE_STORAGE_BUCKET=..."
echo "   REACT_APP_FIREBASE_MESSAGING_SENDER_ID=..."
echo "   REACT_APP_FIREBASE_APP_ID=..."
echo ""
echo "7. En Firebase Console → Authentication → Habilita Google Sign-In"
echo ""
echo "✅ Firebase configurado!"
echo ""

echo "📦 PASO 2: Instalar dependencias"
echo "================================="
echo ""
echo "Ejecuta en terminal:"
echo "  $ npm install"
echo "  $ cd backend && npm install && cd .."
echo ""
echo "✅ Dependencias instaladas!"
echo ""

echo "💾 PASO 3: Inicializar Base de Datos"
echo "===================================="
echo ""
echo "1. Abre una terminal en la carpeta 'backend'"
echo "   $ cd backend"
echo ""
echo "2. Ejecuta el script de inicialización:"
echo "   $ npm run init-data"
echo ""
echo "Esto creará:"
echo "  • 2 Desarrolladores de ejemplo"
echo "  • 3 Campañas promocionales"
echo "  • 4 Códigos de descuento"
echo ""
echo "✅ Base de datos inicializada!"
echo ""

echo "▶️  PASO 4: Ejecutar el Proyecto"
echo "==============================="
echo ""
echo "Terminal 1 - Backend (Puerto 3001):"
echo "  $ cd backend"
echo "  $ npm start"
echo ""
echo "Terminal 2 - Frontend (Puerto 3000):"
echo "  $ npm start"
echo ""
echo "Luego abre: http://localhost:3000"
echo ""
echo "✅ ¡Sistema ejecutándose!"
echo ""

echo "👤 PASO 5: Acceso de Admin"
echo "========================="
echo ""
echo "Email admin: di.ck.nina29@gmail.com"
echo "Contraseña: (Crea una cuenta con este email)"
echo ""
echo "Características admin:"
echo "  • Dashboard con estadísticas"
echo "  • Gestionar campañas"
echo "  • Crear códigos de descuento"
echo "  • Editar perfiles de desarrolladores"
echo ""

echo "📱 PASO 6: Navegación"
echo "===================="
echo ""
echo "Menu principal:"
echo "  • Inicio: Página principal con hero section"
echo "  • Servicios: Catálogo de servicios"
echo "  • Comunidad: Red social de desarrolladores"
echo "  • Acerca de: Información y equipo"
echo "  • Admin: Panel administrativo (solo admin)"
echo ""

echo "🔗 URLS ÚTILES"
echo "============="
echo ""
echo "Frontend:     http://localhost:3000"
echo "Backend:      http://localhost:3001"
echo "Firebase:     https://console.firebase.google.com"
echo "GitHub Code:  https://github.com/richy1991"
echo ""

echo "⚠️  TROUBLESHOOTING"
echo "=================="
echo ""
echo "❌ Puerto 3000/3001 en uso:"
echo "   Cambia el puerto en package.json o variable PORT"
echo ""
echo "❌ Firebase no funciona:"
echo "   Verifica que .env.local esté en la raíz"
echo "   Reinicia: npm start"
echo ""
echo "❌ Error CORS:"
echo "   Asegúrate de que backend está en http://localhost:3001"
echo ""
echo "❌ npm install falla:"
echo "   npm cache clean --force"
echo "   npm install --legacy-peer-deps"
echo ""

echo "📚 DOCUMENTACIÓN"
echo "================"
echo "Lee README.md para más información"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✨ ¡Listo para comenzar! ✨                              ║"
echo "║                                                            ║"
echo "║  Cualquier duda: di.ck.nina29@gmail.com                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
